[tools]
ruby = "latest"
python = "latest"
uv = "latest"
terraform = "1.5.4"
yarn = "1.22.22"

[settings]
# Mise will read from .python-version and .tool-versions, but will not use
# the virtual env created by uv by default. Setting the below allows mise to use the uv venv
python.uv_venv_auto = true
